import Head from "next/head";
import Layout from "../HOC/Layout/Layout";
// import styles from "../styles/Home.module.css";
import Home from "./HomePage/index";
export default function Index() {
  return (
    <Layout>
      <div className={ `` }>
        {/* <div> */ }
        <Head>
          <title>HUB IT GROUP PVT LTD.</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/hubitLogo.svg" />
          <meta name="msvalidate.01" content="DCD5FD5B8698F83AE6AC76EE889570AC" />
        </Head>
        <main>
          <Home />
          
        </main>

      </div>
    </Layout>
  );
}
