import Head from "next/head";
import Layout from "../HOC/Layout/Layout";
// import styles from "../styles/Home.module.css";
import Home from "./HomePage/index";
export default function Index() {
  return (
    <Layout>
      <div className={ `` }>
        {/* <div> */ }
        <Head>
          <title>Hubit</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
          <Home />
        </main>
      </div>
    </Layout>
  );
}
